KafkaCfg:
  Addr: "127.0.0.1:9092"
  AircraftDataTopic: "AircraftData10Area"
  AircraftEventTopic: "AircraftEvent10Area"
RedisCfg:
  Port: 6379
  StatusDBno: 5
  EventDBno: 6
  AircraftDBno: 7
  TaskInfoDBno: 8
  Host: "127.0.0.1"
MySqlCfg:
  Usr: "go"
  Psw: "Zhonglaoshizhen6!"
  Host: "127.0.0.1"
  DB: "systemdb"
  FlightDB: "flightdb"
  EventDB: "eventdb"
  Port: 3306
ClickHouseCfg:
  Host: "127.0.0.1"
  Port: 9000
  Username: default
  Password: zhonglaoshizhen6
  FlightDatabase: flightdb
  EventDatabase: eventdb
  BatchSize: 1000
  EventBatchSize: 10
  FlushPeriod: 30
  EventFlushPeriod: 30
  FlightColumn: ["Longitude", "Latitude", "Altitude", "Yaw", "DataTime"]
  EventColumn: ["DataTime", "Event"]
MongoCfg:
  Host: "127.0.0.1"
  Port: 27777
  Usr: "admin"
  Psw: "21312085PengChengJing!"
  LaneDataDB: "lanedatadb"
  AreaDB: "areadb"
  RasterDB: "rasterdb"
