KafkaCfg:
  Addr: "175.178.125.164:9092"
  AircraftDataTopic: "AircraftData10Area"
  AircraftEventTopic: "AircraftEvent10Area"
RedisCfg:
  Port: 6379
  StatusDBno: 5
  EventDBno: 6
  AircraftDBno: 7
  TaskInfoDBno: 8
  Host: "119.29.181.98"
MySqlCfg:
  Usr: "root"
  Psw: "Zhonglaoshizhen6!"
  Host: "127.0.0.1"
  DB: "systemdb"
  FlightDB: "flightdb"
  EventDB: "flighteventdb"
  Port: 3306