KafkaCfg:
  Addr: "127.0.0.1:9092"
  AircraftDataTopic: "AircraftData10Area"
  AircraftEventTopic: "AircraftEvent10Area"
RedisCfg:
  Port: 6379
  StatusDBno: 5
  EventDBno: 6
  AircraftDBno: 7
  TaskInfoDBno: 8
  Host: "127.0.0.1"
MySqlCfg:
  Usr: "go"
  Psw: "Zhonglaoshizhen6!"
  Host: "127.0.0.1"
  DB: "systemdb"
  FlightDB: "flightdb"
  EventDB: "eventdb"
  Port: 3306
  FlightColumn: [ "Longitude", "Latitude", "Altitude", "Yaw", "DataTime" ]
  EventColumn: [ "DataTime", "Event" ]
  FlightInterval: 60
  EventInterval: 60
ClickHouseCfg:
  Host: "127.0.0.1"
  Port: 9000
  Username: "default"
  Password: "Zhonglaoshizhen6!"
  FlightDatabase: "flightdb"
  EventDatabase: "eventdb"
  BatchSize: 10
  EventBatchSize: 5
  FlushPeriod: 1
  EventFlushPeriod: 1
  FlightColumn: ["Longitude", "Latitude", "Altitude", "Yaw", "DataTime"]
  EventColumn: ["DataTime", "Event"]
MongoCfg:
  Host: "127.0.0.1"
  Port: 27777
  Usr: "admin"
  Psw: "21312085PengChengJing!"
  AreaDB: "areadb"
