EventKafkaPartitionNum: 5 # 事件 Kafka 分区数量
DataKafkaPartitionNum: 25 # 数据 Kafka 分区数量
DBConfigPath: "config/db_config.yaml" # 数据库配置路径
DataUploadPort: 26969 # 数据上传端口
DataReceivePort: 26868 # 数据接收端口
IDPort: 27070 # ID 端口
TaskPort: 27171 # 任务端口
LanePort: 27272 # 车道端口
AreaPort: 27373 # 区域端口
TypePort: 27474 # 类型端口
SaveLogToFile: False # 是否保存日志到文件